// Generated by gencpp from file learning_ros/WordCount.msg
// DO NOT EDIT!


#ifndef LEARNING_ROS_MESSAGE_WORDCOUNT_H
#define LEARNING_ROS_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <learning_ros/WordCountRequest.h>
#include <learning_ros/WordCountResponse.h>


namespace learning_ros
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace learning_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_ros::WordCount > {
  static const char* value()
  {
    return "4dd4fc0aa84b04c0886a72138fb27c19";
  }

  static const char* value(const ::learning_ros::WordCount&) { return value(); }
};

template<>
struct DataType< ::learning_ros::WordCount > {
  static const char* value()
  {
    return "learning_ros/WordCount";
  }

  static const char* value(const ::learning_ros::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::learning_ros::WordCountRequest> should match 
// service_traits::MD5Sum< ::learning_ros::WordCount > 
template<>
struct MD5Sum< ::learning_ros::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_ros::WordCount >::value();
  }
  static const char* value(const ::learning_ros::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_ros::WordCountRequest> should match 
// service_traits::DataType< ::learning_ros::WordCount > 
template<>
struct DataType< ::learning_ros::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::learning_ros::WordCount >::value();
  }
  static const char* value(const ::learning_ros::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_ros::WordCountResponse> should match 
// service_traits::MD5Sum< ::learning_ros::WordCount > 
template<>
struct MD5Sum< ::learning_ros::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_ros::WordCount >::value();
  }
  static const char* value(const ::learning_ros::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_ros::WordCountResponse> should match 
// service_traits::DataType< ::learning_ros::WordCount > 
template<>
struct DataType< ::learning_ros::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::learning_ros::WordCount >::value();
  }
  static const char* value(const ::learning_ros::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_ROS_MESSAGE_WORDCOUNT_H
