// Generated by gencpp from file interfacing/velocity.msg
// DO NOT EDIT!


#ifndef INTERFACING_MESSAGE_VELOCITY_H
#define INTERFACING_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interfacing
{
template <class ContainerAllocator>
struct velocity_
{
  typedef velocity_<ContainerAllocator> Type;

  velocity_()
    : leftwheel(0)
    , rightwheel(0)  {
    }
  velocity_(const ContainerAllocator& _alloc)
    : leftwheel(0)
    , rightwheel(0)  {
  (void)_alloc;
    }



   typedef int8_t _leftwheel_type;
  _leftwheel_type leftwheel;

   typedef int8_t _rightwheel_type;
  _rightwheel_type rightwheel;





  typedef boost::shared_ptr< ::interfacing::velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interfacing::velocity_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_

typedef ::interfacing::velocity_<std::allocator<void> > velocity;

typedef boost::shared_ptr< ::interfacing::velocity > velocityPtr;
typedef boost::shared_ptr< ::interfacing::velocity const> velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interfacing::velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interfacing::velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interfacing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'interfacing': ['/home/blackbox/catkin_ws/src/interfacing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interfacing::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfacing::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interfacing::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interfacing::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfacing::velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfacing::velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interfacing::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "050be0bd30e74f253725230b282a1e21";
  }

  static const char* value(const ::interfacing::velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x050be0bd30e74f25ULL;
  static const uint64_t static_value2 = 0x3725230b282a1e21ULL;
};

template<class ContainerAllocator>
struct DataType< ::interfacing::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interfacing/velocity";
  }

  static const char* value(const ::interfacing::velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interfacing::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 leftwheel\n\
int8 rightwheel\n\
";
  }

  static const char* value(const ::interfacing::velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interfacing::velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftwheel);
      stream.next(m.rightwheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interfacing::velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interfacing::velocity_<ContainerAllocator>& v)
  {
    s << indent << "leftwheel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.leftwheel);
    s << indent << "rightwheel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rightwheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACING_MESSAGE_VELOCITY_H
